version: "3"

services:
  bmi-cal:
    image: "jamal008/bmi-cal:${TAG}"
    restart: unless-stopped
    container_name: bmi-cal
    ports:
      - "80:80"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,container_name={{.Name}}