version: "3"

services:
  bmi-cal:
    image: "jamal008/bmi-cal:${TAG}"
    container_name: bmi-cal
    ports:
      - "80:80"
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224