version: "3"

services:
  grafana:
    image: grafana/grafana:8.2.6
    restart: unless-stopped
    container_name: grafana
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - tools

  loki:
    image: grafana/loki:2.5.0
    restart: unless-stopped
    container_name: loki
    user: "0"
    volumes:
      - ./config/loki.yaml:/etc/config/loki.yaml
      - loki_data:/tmp/loki
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - tools

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - tools

  docker_exporter:
    image: prometheusnet/docker_exporter
    restart: always
    container_name: docker_exporter
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9417:9417
    networks:
      - tools
    
  blackbox_exporter:
    image: prom/blackbox-exporter:master
    restart: always
    container_name: blackbox_exporter
    volumes:
      - ./config/blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - 9115:9115
    networks:
      - tools

volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}

networks:
  tools:
    external: true