name: Build and push Docker image upon tags

on:
  push:
    tags:
      - v*

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: ${{ github.ref == 'refs/tags/' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jamal008/bmi-cal
          tag_with_ref: true 
          tag_with_sha: false 
          tags: latest
  Deploy_imagas:
    name: Setup env variable on server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test variable github tag_with_ref
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    # - name: Test
    #   run: |
    #     echo $RELEASE_VERSION
    #     echo ${{ env.RELEASE_VERSION }}
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo ${{ env.RELEASE_VERSION }}
          export TAG=${{ env.RELEASE_VERSION }}