name: Build and push Docker image upon tags

on:
  push:
    tags:
      - v*

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: jamal008/bmi-cal
          tag_with_ref: true 
          tag_with_sha: false 
          tags: latest
  Deploy_imagas:
    name: Setup env variable on server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup varibale
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Add varibale tag version on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export TAG=${{ env.RELEASE_VERSION }}
          echo $TAG
    - name: Deploy to Docker compose
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_KEY }}
        ssh_public_key: ${{ secrets.SSH_KEY_PUBLIC }}
        deployment_mode: docker compose
        deploy_path: ${{ secrets.SSH_PATH }}
        stack_file_name: docker-compose.yaml
        args: bmi-cal