name: Build and push Docker image upon tags

on:
  push:
    tags:
      - v*

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: masfer/intrajasa
          tag_with_ref: true 
          tag_with_sha: false 
          tags: latest
  Deploy_imagas:
    name: Setup env variable on server and Deploy to Docker compose
    needs: [ push_to_registry ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup varibale
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Add varibale tag version on server and Deploy to Docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          export TAG=${{ env.RELEASE_VERSION }}
          echo $TAG
          cd  ${{ secrets.SSH_PATH }} && sudo docker compose -f docker-compose.yaml up -d
